consumes:
  - application/json
info:
  description: "Simple Go Api for AjoCard Project"
  version: "1.0.0"
  title: "AjoCard-http-go-server"
  contact:
    email: "shekarau.buba@outlook.com"
produces:
  - application/json
schemes:
  - http
swagger: "2.0"
paths:
  /healthz:
    get:
      operationId: "checkHealth"
      produces:
        - text/plain
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
            enum:
              - OK

  /hello/{user}:
    get:
      description: "Return Greeting to user"
      parameters:
        - name: user
          type: string
          required: true
          in: path
      responses:
        "200":
          description: "Returns the greeting"
          schema:
            type: string
        "400":
          description: "Invalid character in 'user' were provided"